### ISSUE TITLE
Going to PostPage does not remove MapPage underneath

### ISSUE THREAD

**Issue by jeffzheng13** [Steelhacks-2023/Lost-At-Pitt#11]
TO RECREATE:

PRECONDITIONS: Navigate to the PostPage via the NavBar at the top, by clicking the list icon.

EXECUTION STEPS: Clicking on a PostCard on the PostPage brings up either the red and green alert dialog, or a form to submit for lost/found item.

EXPECTED BEHAVIOR: Clicking brings up the picture or more details of the lost/found item.

**Comment by tbeidlershenk** [comment]
I know exactly why this is @jeffzheng13 I'll work on it soon
