### ISSUE TITLE
Document future features as Issues

### ISSUE THREAD

**Issue by tbeidlershenk** [Steelhacks-2023/Lost-At-Pitt#24]
What I can think of right now:
1. Need to update database schema with: 
    - User table for their home Geoposition (#2 ) 
    - Their submitted posts
    - Their messages to other users (which we will work on in the future)
2. Need to implement the messaging system between users
3. Filtering / Searching functionality through the current posts in ListView
4. Move database operations to their own file (instead of having "FirebaseFirestore.instance.collection" and add / remove functions everywhere)
5. ... add more

**Comment by jeffzheng13** [comment]
> 1. Need to update database schema with:
>    
>    * User table for their home Geoposition ([Load map at user location  #2](https://github.com/Steelhacks-2023/Lost-At-Pitt/issues/2) )

Why is this necessary? Instead, how about we ask for the user's location and if permission is given we use their current location else we default it to Pitt's official address?

**Comment by tbeidlershenk** [comment]
Sure, but won't we need a user table at some point to store their messages, posts, and any other user data anyway?
