### ISSUE TITLE
Clicking on Map Icon

### ISSUE THREAD

**Issue by jeffzheng13** [Steelhacks-2023/Lost-At-Pitt#3]
Currently clicking on map icon results in out of bounds on mobile devices. Works properly on Windows and MacOS web versions. We can move away from an AlertBox which is the current implementation?

**Comment by tbeidlershenk** [comment]
Yeah I've got a solution to this, we can open a PostPage with the item from the clicked icon. The page is already implemented we just need to update the onTap trigger. It will opens a sub-page overtop the main page (in this case the map) and any clicks inside of that subpage won't register on the map, but the user can return to the map by of clicking outside the sub-page.
