### ISSUE TITLE
User Auth System

### ISSUE THREAD

**Issue by tbeidlershenk** [Steelhacks-2023/Lost-At-Pitt#9]
Might be too big of an enhancement to label as an issue, but moving forward we definitely want to implement a user system so that we can (potentially) have in-app messaging when users are working to get lost items returned. Maybe this is much more complex to be worth it, though. 

We can re-use the sign in page from Remedi and tweak the styling to fit with our app style.

@jeffzheng13 Add any thoughts you have to this as well

**Comment by jeffzheng13** [comment]
For now, we can just use Firebase Auth as the way to go and mandate a .pitt.edu email, but in the future we can think about SSO and SAML incorporation.

**Comment by jeffzheng13** [comment]
Duplicate, closed see #23 .
